### PR TITLE
Add an http::errors::layer to translate errors

### PR DESCRIPTION
**Pull request by seanmonstar**
This is just the beginning of it, to be used by other pieces later.

### CODE REVIEW

**Comment by seanmonstar** [comment]
Hmmm, should this be part of `app` instead? Seems like a similar role to `app::classify`...

**Comment by olix0r** [comment]
@seanmonstar wdyt about moving `map_err_to_5xx` to `app` and making the layer take a `ToStatus` (or something) generic argument -- or even just a pure `fn` if that works out?

**Comment by seanmonstar** [comment]
I've been planning as well to add support to create an appropriate h2 reason if the request was h2 (like refused).

**Comment by seanmonstar** [comment]
For now, I've just moved it entire to `app::errors`.

**Pull request merged**
