### PR TITLE
Try reducing CI flakiness by reducing RUST_TEST_THREADS to 1

### PR DESCRIPTION
**Pull request by seanmonstar**
Just trying this out to see if it passes, if it does, I'll remove all the `flaky_test` cfgs as well.

### CODE REVIEW

**Comment by hawkw** [comment]
Thanks for trying this out! It would be really great to run all those tests on CI.

We should probably try running this multiple times before merging it. Also, I think some of the flaky tests are flaky locally as well, and I'm not convinced that reduced test concurrency will fix _all_ of them...

**Comment by seanmonstar** [comment]
By increasing `RUST_TEST_PATIENCE_MS` to `200`, this passed once. I'll restart the build a couple times.

**Comment by hawkw** [comment]
Huh, I thought we were already setting a higher `TEST_PATIENCE_MS` on Travis, but apparently not!

**Comment by seanmonstar** [comment]
>  Ran for 6 min 43 sec 

2nd build passed, restarting again.

**Comment by seanmonstar** [comment]
>  Ran for 8 min 34 sec 

3rd build passed...

**Comment by hawkw** [comment]
Sporadic CI failures appear to be back: https://travis-ci.org/linkerd/linkerd2-proxy/builds/481582410?utm_source=github_status&utm_medium=notification

**Pull request merged**
