### PR TITLE
Fix HTTP2 requests that don't have an :authority

### PR DESCRIPTION
**Pull request by seanmonstar**
Closes https://github.com/linkerd/linkerd2/issues/2942

### CODE REVIEW

**Comment by seanmonstar** [comment]
I don't quite understand the question.

**Comment by olix0r** [comment]
@seanmonstar when the outbound proxy receives an h2 request without an `:authority`, will an orig-proto header be set on such a request? What value would be set?

When an inbound proxy receives such a request, how will the request that is issued to the target server differ from the original request sent by the client?

**Comment by seanmonstar** [comment]
> when the outbound proxy receives an h2 request without an :authority, will an orig-proto header be set on such a request?

No, orig-proto only upgrades outbound h1. If the proxy received an h2 request (with or without an :authority), it never goes through the orig-proto middleware.

**Comment by olix0r** [comment]
@seanmonstar okay, so the http version mutation occurs inside of the client and not the server -- so linkerd is dealing with the h2 version until the request is completely handled by the proxy... I was unclear whether this change impacted the server or client side of the h2 stack.

**Comment by seanmonstar** [comment]
Yes, this version mutation is a line before handing it over to hyper's client.

**Pull request merged**
