### PR TITLE
remove fs-watch crate

### PR DESCRIPTION
**Pull request by jxs**
closes [linkerd2/2504](https://github.com/linkerd/linkerd2/issues/2504)

### CODE REVIEW

**Comment by olix0r** [comment]
@jxs Thanks, I appreciate this. I'm waiting to merge this until we figure out where this code should go. @carllerche suggested that we may want to feature-flag it in [`tokio-fs`](https://github.com/tokio-rs/tokio/tree/master/tokio-fs)

**Comment by hawkw** [comment]
@olix0r FWIW, even if we just go ahead and delete this now, we can always find the code in the git history if we want to eventually add it to `tokio-fs` or something?

**Comment by olix0r** [comment]
@hawkw that's fair. @jxs if you don't mind fixing the merge conflict, I'd be happy to merge this to master.

**Comment by jxs** [comment]
ok, rebased against master and fixed the merge conflit

**Pull request merged**
