### PR TITLE
ci: Add a linkerd install workflow

### PR DESCRIPTION
**Pull request by olix0r**
We don't currently test that proxy changes are at least usable in a
basic Linkerd installation. This adds a CI workflow to test all Linkerd
code changes against a real k8s cluster with the control plane from the
most recent edge release.

### CODE REVIEW

**Comment by hawkw** [comment]
looks like the build is [busted on the latest nightly](https://github.com/linkerd/linkerd2-proxy/actions/runs/4284396596/jobs/7461291672) --- this looks like a regression to an issue i feel like we've seen before, at first glance

**Review by mateiidavid — APPROVED** [review]

**Comment by hawkw** [comment]
> looks like the build is [busted on the latest nightly](https://github.com/linkerd/linkerd2-proxy/actions/runs/4284396596/jobs/7461291672) --- this looks like a regression to an issue i feel like we've seen before, at first glance

Oh, apparently this is slightly different, it's a warning now. Should be trivial to fix.

**Comment by hawkw** [comment]
#2275 should hopefully fix the nightly build failure.

**Review by hawkw — APPROVED** [review]
very nice, the new `just` recipes will also make manual testing with dev builds of the proxy much easier!

**Pull request merged**
