### PR TITLE
Disable influxdb port detection

### PR DESCRIPTION
**Pull request by tsupertramp**
InfluxDB does not work with linkerd proxy.

### CODE REVIEW

**Comment by olix0r** [comment]
Unfortunately, 8086 is a very common, unregistered port. For instance, we serve the controller's proxy api on 8086.  I'm not sure that this is a good candidate for default configuratoin...

**Comment by tsupertramp** [comment]
You are right. Sorry did not check that.
Thought it was an IANA assigned port.

What about adding influxdb protocol just to the docs so there is one more example or even create a page just with protocols which are unsupported? - No need for autodection. Just some hint that it won't work.

**Comment by tsupertramp** [comment]
You are right. Sorry did not check that.
Thought it was an IANA assigned port.

What about adding influxdb protocol just to the docs so there is one more example or even create a page just with protocols which are unsupported? - No need for autodection. Just some hint that it won't work.

**Comment by olix0r** [comment]
@tsupertramp yeah, i definitely think we should it add it to the docs! Would you like to take a crack at that change? I believe that would go here: https://github.com/linkerd/website/blob/master/linkerd.io/content/2/adding-your-service/_index.md#server-speaks-first-protocols

**Comment by tsupertramp** [comment]
I am closing this one in the meantime. Thanks!

**Pull request closed without merging**
